version: '3.8'

services:
  frontend:
    build: .
    ports:
      - '3000:80'
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
  backend:
    build:
      context: ./server
    ports:
      - '8080:8080'
